### ISSUE TITLE
The action log is different with the sample in readme

### ISSUE THREAD

**Issue by Shylock-Hg** [check-spelling/check-spelling#11]
I simply copy the template to my project as readme said, and push it. But the action log don't show the file/line/misspell. It's a little strange in https://github.com/vesoft-inc/nebula-common/runs/2293391112 .
Does I do wrong something?

**Comment by Shylock-Hg** [comment]
I guess it's exited for the write permission of the forked repo. So I think the action could run still when the post comment failed and print the log in action.

**Comment by Shylock-Hg** [comment]
And I tried the `pull_request_target` event, but it don't works well too. https://github.com/Shylock-Hg/nebula-common/runs/2293565440?check_suite_focus=true

**Comment by jsoref** [comment]
Sometimes you're getting the messages: https://github.com/Shylock-Hg/nebula-common/runs/2294719283#step:4:36

I think the reason you're not seeing the warnings you're expecting is that the words weren't introduced in the version of the commit it's looking at.

For 0.0.18-alpha (not released yet), it should include messages for all files instead of just the ones you changed (I redesigned the checking so that it could do this).

You can try using `@prerelease` if you are up for it.

The exit is just its way of telling GitHub that it found errors and wants its check status to be ❌ .

-- you can use `with: debug: 1` if you want to see it think through things.

**Comment by Shylock-Hg** [comment]
> Sometimes you're getting the messages: https://github.com/Shylock-Hg/nebula-common/runs/2294719283#step:4:36
> 
> I think the reason you're not seeing the warnings you're expecting is that the words weren't introduced in the version of the commit it's looking at.
> 
> For 0.0.18-alpha (not released yet), it should include messages for all files instead of just the ones you changed (I redesigned the checking so that it could do this).
> 
> You can try using `@prerelease` if you are up for it.
> 
> The exit is just its way of telling GitHub that it found errors and wants its check status to be ❌ .
> 
> -- you can use `with: debug: 1` if you want to see it think through things.

Thanks for your answer.
