### ISSUE TITLE
Some files were were [sic] automatically ignored

### ISSUE THREAD

**Issue by htcfreek** [check-spelling/check-spelling#12]
Version: 1.8 (PowerToys Repository)

![20210511_233852.jpg](https://user-images.githubusercontent.com/61519853/117888384-47980500-b2b2-11eb-8b9f-1af76191a15a.jpg)

**Comment by jsoref** [comment]
Thanks. Fixed in `prerelease`. I'm still working on a couple of things for the next release, but I'm hoping to ship this weekend.

Currently stuck trying to figure out why `"::set-output name=...::...` isn't working, once I get that, I'd be happy to ship. (I may also just ship w/o it.)

**Comment by jsoref** [comment]
Fwiw, I finally figured out the `set-output` thing, although I haven't figured out the release part. I'm still hoping i'm close.

**Comment by jsoref** [comment]
As of https://github.com/check-spelling/check-spelling/commit/f1a3b1d89ea5942f2e3d111381e47da2d7133761, check-spelling (in [preprelease](https://github.com/check-spelling/check-spelling/commits/prerelease)) will now scream at me if I make the same mistake going forward. Admittedly, it's going to cause me a bit of pain, since I actually have a valid case for duplicating "words", but I'll cross that bridge when I trip over it.
