### ISSUE TITLE
Disable bot comments on PR

### ISSUE THREAD

**Issue by abdysn2** [check-spelling/check-spelling#17]
It would be nice if there is a flag to disable the bot from commenting on a PR. IMO the bot comments are redundant, since the information can be accessed from the logs directly.

If you are willing to accept this feature request, then i am more than happy to implement it.

**Comment by abdysn2** [comment]
NVM, found https://github.com/check-spelling/check-spelling/blob/main/action.yml#L45, It would be nice though if the flag was documented in https://github.com/check-spelling/check-spelling/wiki/Configuration.
Thanks.

**Comment by jsoref** [comment]
@abdysn2 thanks for the feedback, I've updated https://github.com/check-spelling/check-spelling/wiki/Configuration#post_comment

The post_comment feature is actually a very recent feature.

Please let me know if there's anything else that needs to be improved.

Note that at present the wiki is open to contributions, so if you think a change can be safely added, I'm relatively open to others making it directly to the wiki. (If I get too much spam, I may be force to revisit this...)

**Comment by abdysn2** [comment]
Thanks josh, i am not used to work with github wikis, so it never crossed my mind that i can contribute to the document.
I was thinking maybe to help you with updating the configuration section (since it does not really need knowledge of the project to update) as a thank you for the project, and i was wondering, what is the difference between [configurations](https://github.com/check-spelling/check-spelling/wiki/Configuration) and [advanced configurations](https://github.com/check-spelling/check-spelling/wiki/Configuration%3A-Advanced)?

**Comment by abdysn2** [comment]
Thanks josh, i am not used to work with github wikis, so it never crossed my mind that i can contribute to the document.
I was thinking maybe to help you with updating the configuration section (since it does not really need knowledge of the project to update) as a thank you for the project, and i was wondering, what is the difference between [configurations](https://github.com/check-spelling/check-spelling/wiki/Configuration) and [advanced configurations](https://github.com/check-spelling/check-spelling/wiki/Configuration%3A-Advanced)?

**Comment by jsoref** [comment]
Advanced things are perhaps better described as "things you probably shouldn't need unless you have a good reason or were already using". I should probably rename it. -- I'm open to suggestions.

They aren't quite deprecated, although some of them are close to. `bucket` + `project` have been mostly replaced by `config`, unless you're a really old consumer (and you probably don't exist) and are using them to store the config outside the git repository.

`GITHUB_TOKEN` is a thing, but usually by default the token you have will work fine, so, it's documented as a thing, but I really don't expect anyone to need to set it.

I use `VERBOSE` for debugging, and someone else could, -- I'm not going to remove it since I use it, but it isn't a normal thing.

And `timeframe` is used by `schedule` which you shouldn't need anymore (it predates the existence of `pull_request_target` as well as the ability to assign permissions using `permissions`).

In general, new things should probably go into the normal configuration section. Things w/ `experimental` in their name probably should get a separate section. I'm actually fairly close to moving them from `experimental` to normal. (I need to fix a couple of bugs and see about shipping a new release.)

**Comment by abdysn2** [comment]
@jsoref Really sorry for the late work, got caught up on work. I updated the wiki with the following changes:

 * `GITHUB_TOKEN`: removed from the advanced page and added its content as a note to the configuration page [GITHUB_TOKEN](https://github.com/check-spelling/check-spelling/wiki/Configuration#github_token) section.
 * `experimental_path`: added to the configuration page.
 * `debug`: added to the advanced page.
 * `capture_output_unknown_words`: added to the configuration page.
 * `capture_output_stale_words`: added to the configuration page.
 * `capture_output_skipped_files`: added to the configuration page.
 * `experimental_commit_note`: added to the configuration page.
 
 Can you please have a look to make sure no mistakes or misunderstandings are made? and if there is can you update me so i would correct them. Thanks.
 
 Also i wanted to point out that both `VERBOSE` and `debug` seems to have the same purpose, maybe instead of them being separated, debug should have levels instead, WDYT? Also it looks like `VERBOSE` can not be passed using the actions.
 
 Thanks.

**Comment by jsoref** [comment]
@abdysn2: thanks for taking the time, I'm not perfectly responsive and understand that people have other things to do. That's for thinking about advanced, yeah, it's unfortunate, it definitely feels like the should be a better word....

`VERBOSE` should be accessible today using `env:` as opposed to using `with:`, and yes, that's weird -- I should offer a `with: verbose: 1`. I clearly haven't used verbose much in a long time.

It looks like you have a stray `>` in the `github_token` text (markdown is _fun_).

And I think the `experimental_commit_note` description probably needs clarification, but that's probably a bug in the `action.yml` file -- it isn't that setting it creates the commit, it's that if a commit is created, this is used for the message. (I know that's complicated.)

Overall, a definite improvement, thanks.
