### ISSUE TITLE
Spelling giving misleading/hard to understand errors

### ISSUE THREAD

**Issue by ellistarn** [check-spelling/check-spelling#21]
https://github.com/aws/karpenter/pull/1060

Complaints of the word "enviction" which isn't used anywhere.

**Comment by jsoref** [comment]
Hi, thanks for the feedback, I've commented showing where it was: https://github.com/aws/karpenter/pull/1060#issuecomment-1003222299

I'm interested in figuring out how best to ensure that people understand the output.

So, my starting point is the comment:
https://github.com/aws/karpenter/pull/1060#issuecomment-1003199110

The are two links (I'm absolutizing the first one because otherwise it'll do something wonky in this repository):
> See the [files](https://github.com/aws/karpenter/pull/1060/files/) view or the [action log](https://github.com/aws/karpenter/actions/runs/1638948228) for details.

Checking the [first link (files)](https://github.com/aws/karpenter/pull/1060/files/) yields this definitely confusing message:
![image](https://user-images.githubusercontent.com/2119212/147796469-d83b8cb8-2268-4c51-a030-53cb288cf437.png)

Because the warning is being mapped by GitHub against the branch for the PR (or the latest version of the PR).

There are 4 commits to imagine when check-spelling runs:

1. The branch base for the PR
2. The branch head of the PR
3. The destination head for the PR
4. The calculated merge of the branch head and the destination head.

Using the [second link (action log)](https://github.com/aws/karpenter/actions/runs/1638948228) 

Leads to a page with this:
![image](https://user-images.githubusercontent.com/2119212/147796567-d1a2b5d4-5476-48e0-8ab8-f229d783091f.png)
> [Spell checking](https://github.com/aws/karpenter/runs/4670200713?check_suite_focus=true)
`enviction` is not a recognized word. (unrecognized-spelling)

Ideally that link would take you straight to:
https://github.com/aws/karpenter/runs/4670200713?check_suite_focus=true#step:4:59
> Warning: pkg/controllers/termination/suite_test.go: line 219, columns 46-54, Warning - `enviction` is not a recognized word. (unrecognized-spelling)

But, sadly, GitHub doesn't do that (yet, I need to beg them to improve their links).

Instead it just takes you to the general view and you have to search for `enviction`, but hopefully that itself isn't too hard.

The [checkout-merge](https://github.com/aws/karpenter/runs/4670200713?check_suite_focus=true#step:3:1) step has:
> Run check-spelling/checkout-merge@v0.0.0
> Run /home/runner/work/_actions/check-spelling/checkout-merge/v0.0.0/merge
> From https://github.com/aws/karpenter
>  * branch            b63346cd662d5d5371b1906792f60dc12957ba3c -> FETCH_HEAD
> HEAD is now at b63346c Do not try to evict mirror pods (#1058)
> From https://github.com/aws/karpenter
>  * branch            ab2453e7f032a096ab25ee5d178f12f562307956 -> FETCH_HEAD
> Merge made by the 'ort' strategy.
>  pkg/controllers/provisioning/provisioner.go |  6 ++---
>  pkg/test/expectations/expectations.go       | 41 ++++++++++++-----------------
>  2 files changed, 20 insertions(+), 27 deletions(-)

Basically, checkout-merge is generating a merge between [aws:main](https://github.com/aws/karpenter/commit/b63346cd662d5d5371b1906792f60dc12957ba3c) and the [PR head](https://github.com/aws/karpenter/commit/ab2453e7f032a096ab25ee5d178f12f562307956)

Until recently, I used [@actions/checkout](https://github.com/actions/checkout) to get the `refs/pull/1060/merge` reference -- but I've discovered that at times it yields the wrong thing (a stale merge if the current branch head has conflicts with the destination), and when it fails (because there's initially no valid merge), the error is absolutely incomprehensible and people blame check-spelling for being broken.

Anyway, while the PR didn't change the file to add the typo, the base branch did add it (probably getting merged after spell-check but before branch protection kicked in):

https://github.com/aws/karpenter/blob/b63346cd662d5d5371b1906792f60dc12957ba3c/pkg/controllers/termination/suite_test.go#L219
>			// Expect mirror pod to not be queued for enviction

So.... That's how I'd debug this confusing error.

The question I have for anyone reading this is: How could I improve the messaging to make it easier for someone to get to the same point?

Note: if you don't want to spell check the merge, the workflow can be simplified to just spell check the branch.

The downside of just spell checking the branch is a different race (everything's a race -- this race was someone adding a typo to main after a branch started and then confusing the PR author for the branch).

Consider a repository with a single instance of a boutique word `myunusualword`. To make check-spelling happy, it's added to `expect.txt`.

In one branch, someone deletes the line (or file) containing `myunusualword` and adds some other new word `myotherword`. check-spelling suggests adding the new word to `expect.txt` and removing the now unused word from `expect.txt`. The branch author does this.

In branch two, someone copies `myunusualword` to a new location. check-spelling for the branch is happy w/ this because it's already in expect.

The first branch is converted into a PR and merged.

The second branch is converted into a PR. If you only check-spelling of the branch, everything is happy `expect.txt` has `myunusualword` and it's present in two locations. If you check the merge, check-spelling will be unhappy because it's only present in one location and has been removed from `expect.txt`.

Assuming that you don't check the merge, everyone's happy, you merge the PR, and then check-spelling runs on `main`. And screams that `myunusualword` is unrecognized.

To make things even more frustrating, another user chooses this exact moment to create a fork, and they make a change that doesn't add any unknown words. And check-spelling yells at them about `myunusualword` because it was added by that most recent PR and the `expect.txt` reference was removed in the previously merged PR.

Anyway, that's the reason that I prefer/encourage checking the merge. It's slightly less likely to lead to unhappy outcomes.

Sadly, it does mean that at the initial landing, it's important to go through and poke each pending PR to make sure that they don't introduce typos as https://github.com/aws/karpenter/pull/1058 did in https://github.com/aws/karpenter/commit/b63346cd662d5d5371b1906792f60dc12957ba3c 

I know this is a lot to take in, if there's a Slack you're on or there's some other media, I'd be more than happy to talk things through if that's preferable. I really do want each part of the process to be as smooth as possible.

**Comment by jsoref** [comment]
I believe this is fixed with https://github.com/check-spelling/check-spelling/releases/tag/v0.0.22 -- while working on this release I found a couple of places where check-spelling effectively lost track of the information it had about words like this and fixed it so that it should consistently report items that it finds.
