### ISSUE TITLE
Is it possible to use remote dictionaries

### ISSUE THREAD

**Issue by tas50** [check-spelling/check-spelling#31]
If I have a repo in my org with a single dictionary file can I use that in each of my actions?

**Comment by jsoref** [comment]
Sure:
https://github.com/check-spelling/check-spelling/blob/729687234a293e0680b12ca055a02fff415da89d/action.yml#L26-L28

**Comment by jsoref** [comment]
Does this make sense? And is there anything that could help you get to this?

The public facing documentation is here:
https://github.com/check-spelling/check-spelling/wiki/Configuration#dictionary_url

But, if the documentation isn't sufficient for you to understand how to use it, then it needs to be improved.

**Comment by tas50** [comment]
I ended up providing our own `dictionary_source_prefixes` and then adding a new dictionary for our company:

https://github.com/mondoohq/mondoo-operator/blob/main/.github/workflows/spell-check.yaml#L33

**Comment by jsoref** [comment]
Yeah, that sounds like a good approach.

One warning. The `cspell:` alias for v0.0.20's `check_extra_dictionaries` uses [`v20220427`](https://github.com/check-spelling/cspell-dicts/tree/v20220427/dictionaries/):
https://github.com/check-spelling/check-spelling/blob/v0.0.20/action.yml#L67-L101
https://github.com/check-spelling/check-spelling/blob/729687234a293e0680b12ca055a02fff415da89d/action.yml#L67-L101
and it may be moderately annoyed if any of the dictionaries it's looking for aren't present in the same locations as in [`v20220816`](https://github.com/check-spelling/cspell-dicts/tree/v20220816/dictionaries/) (which is what `prerelease` is currently using):
https://github.com/check-spelling/check-spelling/blob/prerelease/action.yml#L67-L141
https://github.com/check-spelling/check-spelling/blob/5a1d6a43b51b5158b45dd134261a72562818ced5/action.yml#L67-L141

---

It's _possible_ I'll do another refresh between now and v0.0.21. I haven't decided. The current prerelease is a significant improvement in dictionary quality, but the upstream does improve with time, and there's some value in me being able to let people fairly easily select dictionaries. -- While it's possible to update the base dictionary, I'm fairly skittish about doing so, and think it'll be much easier for me to just move the supplements, since people could just add in the urls or prefixed versions for older versions if they so desire.
