### ISSUE TITLE
Different order of words in expect.txt yields different results. Expected?

### ISSUE THREAD

**Issue by 0liver** [check-spelling/check-spelling#33]
We're spell-checking a large solution of ours and have a long list of words in _expect.txt_.

Today I had to add both `lintrc` and `Lintrc` to that file because I use those words as placeholders for all `*lintrc` files.

To my surprise, the following order resulted in an [error](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3332843606/jobs/5514175896):

```txt
# more
Lintrc
lintrc
# more
```

I tried to invert the order, and that [succeeded](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3332813516/jobs/5514110277):

```txt
# more
lintrc
Lintrc
# more
```

This looks like a bug to me, and a subtle one. What's your take?

**Comment by jsoref** [comment]
The spell checker indeed isn't a particular fan of having both. In general, I'd suggest using `allow.txt` for things like this (you can put both, and it won't care if the words come/go from your corpus).

I haven't spent enough time trying to understand what it's thinking. It mostly stems from a very old architectural decision that was very helpful before I wrote check-spelling, but which hasn't really served it particularly well in its role here.

Basically, check-spelling (really `w`/`f`) tends to try to collate related items into something like `lintrc (Lintrc, lintrc)` and think about them like that.

I believe I will eventually remove most of those remnants, but as it'll be a breaking change, I imagine it'll be a bigger version bump (probably to 0.1.x).

Mostly, if you have `lintrc` in expect, you shouldn't need to have `Lintrc`. The idea is that you have a brand `Lintrc` and you've said "it's ok to have `Lintrc`". You haven't said it's ok to have `lintrc`, maybe your brand's style guide insists that it's *always* written `Lintrc`. But if you then go to check-spelling and say `lintrc` is ok, then it'll say "ok, each of `lintrc`, and `Lintrc`, and `LINTRC` are ok", because you can always Sentence-capitalize a word or all-caps a word. When you do that, it will generally suggest removing `Lintrc` from expect.txt to "minimize" the size of the file.

**Comment by 0liver** [comment]
Thank you for taking the time to explain the situation in such great length.

The last paragraph about upper-first-letter and all-lower-case versions of the same word really opened my eyes!
