### ISSUE TITLE
Only doing spellcheck on files in folder

### ISSUE THREAD

**Issue by emilpriver** [check-spelling/check-spelling#36]
How do I only make checks on files in folder?

Let say I have a folder called `blog` and don't want `cool/index.md` to be spellchecked, but `blog/index.md`

**Comment by jsoref** [comment]
use `only.txt`:
```
cool/
```

**Comment by jsoref** [comment]
The alternative is `excludes.txt`:
```
cool/
```

But, your request is for the former...

**Comment by emilpriver** [comment]
Aaah your the best! thanks :D

**Comment by jsoref** [comment]
I should ask which documentation you looked at and how I can work to improve the documentation so that you wouldn't have needed to file an issue. -- In essence, if a user needs to ask a question, it indicates an issue somewhere that should be addressed, even if it doesn't require implementing a new feature. -- And documentation tends to be a real weak spot for projects large and small (it's generally an after-thought, and often written by people who are too familiar w/ a system to know what someone unfamiliar w/ the system would need to know).

That said, the documentation for `only.txt` is reachable from:
https://github.com/check-spelling/check-spelling/wiki/Configuration-information

But, if you didn't land in the [wiki](https://github.com/check-spelling/check-spelling/wiki) or didn't land near that page, that wouldn't have helped you.

I've added a [purpose section](https://github.com/check-spelling/check-spelling/wiki/Configuration-Examples%3A-only#purpose) to [Configuration Examples: only](https://github.com/check-spelling/check-spelling/wiki/Configuration-Examples%3A-only) which should hopefully help in case people land on the page and wonder what it is.

At some point, I'll probably set up an issue template to try to guide people to things... But I'll need to think about that (and at least make my 0.0.21 release first...)
