### ISSUE TITLE
How to tell which file a misspelling is coming from?

### ISSUE THREAD

**Issue by lilith** [check-spelling/check-spelling#4]
I wonder if it would be possible (in the github message) to list the path to the file in which the word first occurs?

**Comment by jsoref** [comment]
0.0.16 should do this in the log or for the first 10 or so in a pretty form

**Comment by jsoref** [comment]
And the log will show the rest.

Note that the first 10 are first come first serve, if the same word is misspelled 10 times, it'll be flagged 10 times drowning out other items. Making it a bit smarter is on my list of things to consider (it roughly requires queuing the list of complaints, and then intentionally sorting them to favor different words instead of first come first serve).

**Comment by jsoref** [comment]
Fwiw, as of v0.0.18, it will in fact list the first file for each item it finds before it lists additional instances.
