### ISSUE TITLE
Add a pattern to exclude URL's

### ISSUE THREAD

**Issue by ricardo-dematos** [check-spelling/check-spelling#40]
I'm trying to add a pattern to exclude URL's addresses from spell checking, but with no success.

```perl
# URL address
(https?|ftp)://(-\.)?([^\s/?\.#-]+\.?)+(/[^\s]*)?
```

In my opinion, this pattern should exist by default.

**Comment by jsoref** [comment]
In principle, something like this should work:
```
(?:https?|ftp)://(?:-\.)?(?:[^\s/?\.#-]+\.?)+(?:/[^\s]*)?
```

Do you have a sample where it doesn't work?

(I'm a bit curious about the `-\.` part do you have urls that are of the form `http://-.x` ?)

[regex buddy](https://regexbuddy.com) has a [fairly compact pattern](https://stackoverflow.com/questions/161738/what-is-the-best-regular-expression-to-check-if-a-string-is-a-valid-url/163684#163684) that could be adapted:
```
(?:\b(?:https?|ftp|file)://)[-A-Za-z0-9+&@#/%?=~_|!:,.;]+[-A-Za-z0-9+&@#/%=~_|]
```

I can easily add something like this into the `check-spelling/spell-check-this` template and thus people can turn them off later since it's copied mutably into their repositories.

---

The problem w/ defaults is that I really don't have a good way to turn them off.

**Comment by jsoref** [comment]
I've tentatively added an entry to candidates: https://github.com/check-spelling/spell-check-this/commit/5d2ff60b3c4b1e60804db3185d9a140026723be3
