### ISSUE TITLE
Review input 'GITHUB_TOKEN'

### ISSUE THREAD

**Issue by ricardo-dematos** [check-spelling/check-spelling#42]
Since that input `GITHUB_TOKEN` default value is `github.token` , there's no need to make it required.

> Important: An action can access the GITHUB_TOKEN through the github.token context even if the workflow does not explicitly pass the GITHUB_TOKEN to the action. As a good security practice, you should always make sure that actions only have the minimum access they require by limiting the permissions granted to the GITHUB_TOKEN. For more information, see "[Permissions for the GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)."

source: [Using the GITHUB_TOKEN in a workflow](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow)

---

Please, consider changing it's name to `token` or `repo-token`, as seen in [actions/setup-python](https://github.com/actions/setup-python) and [actions/labeler](https://github.com/actions/labeler), because it's functionality are similar, thus helping create a standard across the actions available in the [GitHub Marketplace - Actions](https://github.com/marketplace?type=actions).

**Comment by jsoref** [comment]
Fair. I've been thinking about renaming all of my settings. I've been using `_`s because they're easier to reason with in shell, but actions prefer `-`s.

It'll be a slight migration headache.

I've also been considering moving _most_ of my settings out of the workflow and into a state file. This (and a configuration path) would of course remain, but I'm considering moving most others away, which would resolve a number of points for me...

The `required` field is mostly unenforced by GitHub. What I'm trying to say is that people shouldn't do:

```yaml
  with:
    GITHUB_TOKEN: ""
```

Which would otherwise be legal, but I promise that doing that will not result in a good outcome (as a very large portion of the engine involves talking to GitHub).

(I should add a caveat in that [Gitea is previewing actions](https://blog.gitea.io/2022/12/feature-preview-gitea-actions/) and I hope (but haven't tested) that it will work with GHES, and it should generally work with [nektos/act](https://github.com/nektos/act), so it doesn't precisely need GitHub, it just really wants a GitHub-like environment -- including a token so it can talk to the GitHub-like api server.)

Renaming fields is something I definitely want to do before a 1.0 release (at which point I'd likely drop a number of deprecated fields).

**Comment by jsoref** [comment]
The documentation doesn't really explain enough of these things, so I'm not entirely certain if the statement is technically right or wrong:
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputsinput_idrequired
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputsinput_iddefault

I suppose I could file a bug asking for the documentation to clarify what they mean.

I'll have to test to see what explodes.

I'll probably deprecate `GITHUB_TOKEN` (at which point I'll drop the `required` and `default`) and then add a `token` w/ a default of `github.token` and then use `GITHUB_TOKEN` if present and `token` if not....

**Comment by jsoref** [comment]
Fwiw, I've started working on these things. I expect to include changes in prerelease shortly.

**Comment by jsoref** [comment]
I ran into a bunch of snags trying to redo all of my inputs and punted on this work, so it is not include in v0.0.22. I do intend to work on it.

**Comment by jsoref** [comment]
I've shipped [v0.0.23](https://github.com/check-spelling/check-spelling/releases/tag/v0.0.23).

Sadly, I missed fixing this. I'll pull it in today so that the next release will have it. 

I will need to review the docs and decide if I need to file bugs/PRs about it...

**Comment by jsoref** [comment]
Fixed in https://github.com/check-spelling/check-spelling/releases/v0.0.24
