### ISSUE TITLE
Add description to allow.txt

### ISSUE THREAD

**Issue by olblak** [check-spelling/check-spelling#52]
Thanks for the project, while using it on updatecli/updatecli.
I faced a situation where I needed to add custom words in the allow.txt and I realize that I would be useful to be able to document them for the future myself.

**Comment by jsoref** [comment]
Hmm, I've generally relied on commit messages and blame for this purpose.

It isn't prominently documented, but `reject.txt` is processed after `allow.txt` which means that if you defined a pattern in `reject.txt`, such as `^#.*` and then prefixed lines of allow with text that matched the pattern `#`, those lines would be dropped (functionally ignored) from the dictionary.

You could probably do other things today as well, especially since today any dictionary entry that contains characters outside `[A-Za-z']` will be ignored (since only those characters are considered valid characters in words). But in the next version, I'm likely to allow projects to relax this constraint to some arbitrary input set: https://docs.check-spelling.dev/Feature:-Configurable-word-characters.html.

Here's an example that I'm fairly certain will work:

### `reject.txt`

```
^#.*
```

### `allow.txt`

```
# contributor's name
soref
```

**Comment by olblak** [comment]
To be honest, I like your suggestion to just run git blame.
I am closing the issue
